// Generated by CoffeeScript 1.3.3

(function() {
  var Song, mongoose, partySchema;
  mongoose = require('mongoose');
  mongoose.connect('mongodb://localhost/party');
  Song = {
    type: String,
    score: Number,
    uri: String,
    timestamp: {
      type: Date,
      "default": Date.now
    }
  };
  partySchema = mongoose.Schema({
    name: String,
    loc: [Number],
    playing: {
      type: Song
    },
    songs: [Song]
  });
  partySchema.index({
    loc: "2d"
  });
  partySchema.methods.voteSong = function(uri, increment) {
    var s, _i, _len, _ref;
    _ref = this.songs;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      s = _ref[_i];
      if (s.uri === uri) {
        s.score += increment;
        this.model('Party').save();
        return s;
      }
    }
  };
  partySchema.methods.upvoteSong = function(uri) {
    return partySchema.methods.voteSong(1);
  };
  partySchema.methods.downvoteSong = function(uri) {
    return partySchema.methods.voteSong(-1);
  };
  partySchema.methods.addSong = function(song) {
    var s, _i, _len, _ref;
    this.songs.push(song);
    this.model('Party').save();
    _ref = this.songs;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      s = _ref[_i];
      if (s.uri === song.uri) {
        return s;
      }
    }
  };
  partySchema.methods.playNextSong = function(uri) {
    return null;
  };
  return module.exports.Party = mongoose.model('Party', partySchema);
})();
