// Generated by CoffeeScript 1.3.3

(function() {
  var partyController, staticController;
  staticController = require('./controllers/static');
  partyController = require('./controllers/party');
  return module.exports.Router = {
    "static": staticController,
    party: partyController
  };
})();
